name: CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Report status
      if: always()
      uses: actions/github-script@v6
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const { owner, repo } = context.repo;
          const { sha } = context.payload;
          const state = '${{ job.status }}' === 'success' ? 'success' : 'failure';
          github.rest.repos.createCommitStatus({
            owner,
            repo,
            sha,
            state,
            target_url: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}',
            description: 'Tests ${{ job.status }}',
            context: 'tests'
          });

